name: Deploy

on:
  push:
    branches: [ignore]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install
        run: npm ci
        env:
          CI: true

      - uses: ./.github/actions/test

      - uses: ./.github/actions/build-node

      - uses: act10ns/slack@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: always()
