name: Deploy

on:
  push:
    branches: [ main, RC/** ]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14 ]

    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/clean

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install
        run: |
          npm ci
        env:
          CI: true

      - uses: ./.github/actions/test

      - uses: ./.github/actions/build-node
