name: Test

on:
  push:
    branches-ignore: [main, RC/**]

jobs:
  npm-test:
    name: npm install & lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install
        run: |
          npm ci
        env:
          CI: true

      - uses: ./.github/actions/test

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          mention: 'channel'
          if_mention: always
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
