name: test
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'

      - name: ci
        run: npm ci

      - name: lint
        run: npm run lint

      - name: send slack message
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: ${{ job.status }}
          fields: repo,message,author,ref,job,took
          author_name: ''
        if: failure()

  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'

      - name: ci
        run: npm ci

      - name: tsc
        run: npm run tsc

      - name: send slack message
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: ${{ job.status }}
          fields: repo,message,author,ref,job,took
          author_name: ''
        if: failure()

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'

      - name: ci
        run: npm ci

      - name: build
        run: npm run build

      - name: send slack message
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: ${{ job.status }}
          fields: repo,message,author,ref,job,took
          author_name: ''
        if: failure()
