name: Test

on: push
#    branches-ignore: [main, RC/**]

jobs:
  npm-test:
    name: npm install & lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install
        run: npm ci
        env:
          CI: true

      - uses: ./.github/actions/test
      - uses: ./.github/actions/build-node

      - uses: act10ns/slack@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: always()
