name: Test

on: push
#    branches-ignore: [main, RC/**]

jobs:
  npm-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install
        run: npm ci

      - uses: ./.github/actions/test
      - uses: ./.github/actions/build-node

      - uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: ${{ job.status }}
          fields: ref,repo,workflow,message,author,took
        if: always()
